import * as React from 'react'

const Doc1 = () => {
    return (<>
    <div className="fontMediu boldMax borderRegular docTitle">Spania</div>
    <div className="fontMediu">Spania :  Legile din Burgos de către Ferdinand Catolicul</div>
    <div className="foto doc1Foto"></div>
    <div className="fontMin docDesc"><span>C</span>ardinalul Arhiepiscopul Domingo de Mendoza de Sevilla a auzit informații despre abuzurile asupra indienilor din America și a trimis un grup de misionari dominicani în Hispaniola pentru a opri maltratările. Ei nu au putut să o oprească din punct de vedere legal, dar misionarii au făcut plângeri și au stârnit o dezbatere de care coloniștii se temeau că îi va face să-și piardă interesele de proprietate; Fray Antonio de Montesinos le-a predicat coloniștilor că păcătuiesc și că nu au dreptul să-i forțeze pe indieni să-i slujească, pretinzând că ar trebui doar convertiți la creștinism.
	<br /><span>C</span>oloniștii nu au fost de acord și au decis că cel mai bun mod de a-și proteja interesele era să se reunească ca un grup și să aleagă un călugăr franciscan pe nume Alonso de Espinal care să-și prezinte cazul regelui Ferdinand al II-lea al Aragonului și fiicei sale, regina Ioana a Castiliei , co-conducători ai Spaniei și respinge acuzațiile lui Montesinos. Planul coloniștilor s-a întors însă, iar Spania a fost revoltată de cazurile de maltratare a indienilor. Pentru a rezolva problema morală și juridică, guvernanții au însărcinat un grup de teologi și academicieni să vină cu o soluție.
    <br /><span>C</span>ălugări și alți academicieni spanioli, ca indienii nativi să nu devină sclavi pentru noii coloniști, i-au făcut presiuni pe regele Ferdinand al II-lea al Aragonului și pe fiica sa, acum regina domnitoare a Castiliei , Ioana I a Castiliei , să adopte un set de legi care să protejeze drepturile nativilor din Lumea Nouă, care urmau să devină legile din 1512 din Burgos. În Burgos, la 27 decembrie 1512, treizeci și cinci de legi au fost puse în aplicare pentru a asigura libertatea popoarelor indigene din America și pentru a aplica regulile de reducere a indienilor care guvernează conversiile.
    <br /><span>M</span>ai jos sunt reprezentate 10 legi din cele 35 implementate:
    <br /><span>1</span>: Indienii vor fi mutați la encomiendas . Pentru fiecare cincizeci de indieni, vor fi construite patru loji (treizeci pe cincisprezece picioare). Acest pământ nu poate fi luat de la ei, deoarece au fost luați din pământul lor inițial. Indienii vor planta toată hrana. În timpul anotimpurilor potrivite, encomenderos (bărbații care se uită peste indieni) îi vor pune pe indieni să planteze porumb și să crească găini.
    <br /><span>2</span>: Indienii își vor părăsi țara de bunăvoie pentru a veni la encomiendas , astfel încât să nu sufere de a fi îndepărtați cu forța.
    <br /><span>3</span>: Cetăţeanul căruia i se dau indienii trebuie să ridice o structură care să fie folosită ca biserică. În biserică trebuie să fie o poză a Maicii Domnului și un clopot cu care să cheme indienii la ora de rugăciune. Persoana care le are în encomienda trebuie să meargă cu ei la biserică în fiecare seară și să se asigure că își fac semnul și cântă mai multe imnuri. Dacă un indian nu vine la biserică, nu are voie să se odihnească a doua zi.
    <br /><span>4</span>: Pentru a ne asigura că indienii învață creștinismul în mod corespunzător, ei vor fi testați la fiecare două săptămâni și vor fi învățați ceea ce nu știu de către Encomendero. El îi va învăţa Cele Zece Porunci , Cele Şapte Păcate Capitale şi Articolele de Credinţă . Orice encomendero care nu face acest lucru corect va fi amendat cu șase pesos de aur .
    <br /><span>5</span>: Se va construi o biserică la echidistanță de toate moșiile. Duminica, va fi oficiată Liturghia și se va mânca un festin. Dacă encomendero -ul nu-și aduce indienii, va fi taxat cu zece pesos de aur.
    <br /><span>6</span>: Dacă biserica este prea departe, se va construi o alta.
    <br /><span>7</span>: Preoții care adună zecimi din moșii trebuie să aibă preoți continuu în bisericile moșiilor.
    <br /><span>8</span>: Vor fi construite biserici la mine, astfel încât indienii care lucrează în mine să poată auzi slujba duminica.
    <br /><span>9</span>: Cine are cincizeci de indieni trebuie să aleagă un băiat pe care encomendero -ul crede că este capabil, să fie învățat să citească și să scrie și, de asemenea, importanța catolicismului. Acest băiat îi va învăța apoi pe ceilalți indieni, deoarece indienii ar accepta mai ușor ceea ce spune băiatul decât ceea ce spun spaniolii. Dacă encomendero are o sută de indieni, vor fi aleși doi băieți. Credința trebuie să fie înrădăcinată în capetele lor, astfel încât sufletele indienilor să fie salvate.
    <br /><span>10</span>: Dacă un indian se îmbolnăvește în apropierea locului unde este un preot, preotul trebuie să meargă la el și să recite Credo și alte lucruri profitabile ale credinței catolice. Indianul trebuie să mărturisească fără să i se plătească o taxă. Dacă indianul va muri, el va fi îngropat cu o cruce lângă biserică. Dacă nu este înmormântat, encomendero -ul datorează o amendă de patru pesos de aur.</div>
    </>)
}

export default Doc1